export const surpriseMePrompts = [
  "A serene sunset over a calm lake.",
  "An old, abandoned factory covered in vines.",
  "A bustling market in a foreign city.",
  "A tranquil garden with colorful flowers in bloom.",
  "A misty mountain peak emerging from the clouds.",
  "A hidden waterfall in a lush rainforest.",
  "A winding path through a sunlit forest.",
  "A quiet beach with waves gently lapping the shore.",
  "A vibrant cityscape at night, illuminated by neon lights.",
  "A field of sunflowers stretching towards the horizon.",
  "A rustic cottage surrounded by rolling hills.",
  "A majestic castle perched atop a rocky cliff.",
  "An underwater scene with coral reefs and colorful marine life.",
  "An ancient temple partially covered in sand.",
  "A dense, fog-covered forest with towering trees.",
  "A futuristic city with flying cars and towering skyscrapers.",
  "A cozy fireplace in a cabin with a view of the snowy mountains.",
  "A tranquil river winding through a lush valley.",
  "A mystical cave entrance hidden behind a waterfall.",
  "A bustling street market with vendors selling exotic goods.",
  "A night sky filled with stars and a bright full moon.",
  "A quaint village nestled in a valley surrounded by hills.",
  "A close-up of dewdrops on vibrant green leaves.",
  "A lone tree standing in the middle of an open field.",
  "A traditional Japanese tea garden with a peaceful pond.",
  "A dramatic lightning storm over an empty desert landscape.",
  "A busy harbor with ships of all sizes docked along the shore.",
  "A charming bookstore with shelves full of books.",
  "A rugged coastal cliff overlooking the crashing waves.",
  "A mountain range covered in snow and ice.",
  "An alleyway in an old European town with cobblestone streets.",
  "A tranquil riverbank with weeping willow trees.",
  "A modern art gallery with unique and vibrant pieces.",
  "A pathway through a bamboo forest.",
  "A hot air balloon soaring over a picturesque landscape.",
  "A colorful field of wildflowers under a bright blue sky.",
  "A serene pond surrounded by vibrant autumn trees.",
  "A mysterious doorway at the end of a long corridor.",
  "A lively carnival with colorful rides and attractions.",
  "A group of friends around a campfire under the starry sky.",
  "A coastal village with colorful houses and fishing boats.",
  "A row of classic bicycles leaning against a brick wall.",
  "A rocky coastline with crashing waves and sea stacks.",
  "A narrow alleyway filled with colorful market stalls.",
  "A tranquil oasis in the middle of a vast desert.",
  "A traditional pagoda against the backdrop of a setting sun.",
  "A grand ballroom with elegant chandeliers and high ceilings.",
  "A snowy village with cozy cottages and twinkling lights.",
  "A mysterious forest with bioluminescent plants.",
  "A bustling city square with street performers and vendors.",
  "A peaceful countryside scene with grazing sheep.",
  "A sunlit field of wild horses.",
  "A sunken shipwreck on the ocean floor.",
  "A charming café with outdoor seating and flowering plants.",
  "A coastal lighthouse overlooking the crashing waves.",
  "A sunflower field with rows of tall, vibrant flowers.",
  "An intricate, ancient mosaic on the floor of a ruin.",
  "A lush tropical island with palm trees and turquoise waters.",
  "A tranquil pagoda in a traditional Japanese garden.",
  "A colorful hot air balloon festival in the sky.",
  "An old windmill against a backdrop of rolling hills.",
  "A cozy cabin surrounded by a snowy landscape.",
  "A busy street in a bustling Asian market.",
  "A majestic waterfall surrounded by lush vegetation.",
  "A serene pond with water lilies and reflection of trees.",
  "A charming cottage covered in ivy.",
  "A desert landscape with towering sand dunes.",
  "A bustling café with people enjoying coffee and pastries.",
  "A serene coastal inlet with boats and calm waters.",
  "A hidden cave entrance with sunlight streaming through.",
  "A quaint village square with a central fountain.",
  "A starry night sky over a tranquil meadow.",
  "A futuristic space station orbiting a distant planet.",
  "A vibrant garden with rows of blooming flowers.",
  "An ancient ruin with intricate carvings and statues.",
  "A peaceful countryside scene with grazing cows.",
  "A magical forest with trees that have faces.",
  "A bustling food market with stalls of exotic fruits and spices.",
  "A tranquil pond with a wooden dock and rowboat.",
  "A grand library with shelves of old books.",
  "A majestic cathedral with stunning architecture.",
  "A quiet stream winding through a lush forest.",
  "A coastal town with colorful houses along the waterfront.",
  "A serene pagoda surrounded by cherry blossoms in full bloom.",
  "A bustling street in a rainy city with colorful umbrellas.",
  "A mystical portal in the middle of a clearing.",
  "A vast savanna with herds of grazing animals.",
  "A charming village with cobblestone streets and thatched-roof cottages.",
  "A tranquil garden path surrounded by blooming flowers.",
  "A medieval castle overlooking a calm lake.",
  "A bustling night market with vibrant lights and crowds.",
  "A hidden cave with ancient petroglyphs on the walls.",
  "A sunlit glade in a dense forest.",
  "A bustling cityscape with futuristic skyscrapers.",
  "A tranquil beach with crystal-clear turquoise waters.",
  "A medieval village square with a bustling market.",
  "A quiet alleyway lined with colorful houses.",
  "A tranquil pond surrounded by autumn trees.",
  "A snowy landscape with a solitary cabin.",
  "A bustling harbor with sailboats and yachts.",
  "A hidden garden with a serene koi pond.",
  "A charming countryside cottage with a thatched roof.",
  "A bustling street in a historic European city.",
  "A serene river with a picturesque bridge.",
  "A futuristic cityscape with flying cars and holographic billboards.",
  "A tranquil meadow with wildflowers and butterflies.",
  "A traditional Chinese garden with a decorative bridge.",
  "A vibrant market square with street performers and vendors.",
  "A hidden waterfall cascading into a clear pool.",
  "A cozy café with outdoor seating and hanging plants.",
  "A tranquil temple courtyard with ornate architecture.",
  "A bustling city square with towering skyscrapers.",
  "A serene forest clearing with sunlight streaming through the trees."
];

export const USER_DALLE = "user_dalle";
export const ACCESS_TOKEN = "access_token";
export const REFRESH_TOKEN = "refresh_token";